services:
  - type: web
    name: signal-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: EMBEDDING_MODEL
        value: hash-embedding-v1
      - key: RERANKER_MODEL
        value: lexical
      - key: APP_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: signal-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: streamlit run frontend/streamlit_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: API_URL
        value: https://signal-api.onrender.com